apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: {{ .Values.global.namespace | default "fastfood" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: fastfoodapp-config
            - secretRef:
                name: fastfoodapp-secret
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
