# User Service Deployment
# Image: your-dockerhub-username/user-service:latest
# Port: 5001
# Replicas: 2
# Env from: configmap, secret
# MONGO_URI: mongodb://mongodb:27017/food_delivery_users


apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-Deployment
  namespace: fastfood
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vignesh8386/fastfoodapp-user-service:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: fastfoodapp-config
            - secretRef:
                name: fastfoodapp-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "256Mi"
            limits:
              memory: "128Mi"
              cpu: "512Mi"
