apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfoodapp-config
  namespace: {{ .Values.global.namespace | default "fastfood" }}
data:
  API_URL: http://api-gateway:5000
  USER_SERVICE_URL: http://user-service-service:5001
  RESTAURANT_SERVICE_URL: http://restaurant-service-service:5002
  ORDER_SERVICE_URL: http://order-service-service:5003
  MONGO_URI: {{ .Values.global.mongodbUri | quote }}
