apiVersion: v1
kind: Secret
metadata:
  name: fastfoodapp-secret
  namespace: {{ .Values.global.namespace | default "fastfood" }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.global.jwtSecretBase64 | quote }}
  JWT_EXPIRE: {{ .Values.global.jwtExpireBase64 | quote }}
